## Steps

In [1]:
#import libraries
#import dataset
#build the model/test
#start making prediction

In [2]:
#import libraries
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
car_price=pd.read_csv(r"C:\Users\Ali Mir\Desktop\ML models\archive (1).zip")

In [4]:
car_price

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,First Owner,18.5 kmpl,1197 CC,82.85 bhp,113.7Nm@ 4000rpm,5.0
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,Fourth & Above Owner,16.8 kmpl,1493 CC,110 bhp,"24@ 1,900-2,750(kgm@ rpm)",5.0
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,First Owner,19.3 kmpl,1248 CC,73.9 bhp,190Nm@ 2000rpm,5.0
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,First Owner,23.57 kmpl,1396 CC,70 bhp,140Nm@ 1800-3000rpm,5.0

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
# deviding our dataset into training and testing 
train_data,test_data= train_test_split( car_price, test_size=0.25, random_state=0)

In [7]:
train_data

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
4313,Hyundai i10 Magna,2012,267000,40000,Petrol,Individual,Manual,First Owner,20.36 kmpl,1197 CC,78.9 bhp,111.7Nm@ 4000rpm,5.0
5178,Mercedes-Benz New C-Class 200 K AT,2007,500000,120000,Petrol,Individual,Automatic,First Owner,11.7 kmpl,1796 CC,178 bhp,"24.5@ 3,500-4,500(kgm@ rpm)",5.0
758,Hyundai EON D Lite,2013,200000,80000,Petrol,Individual,Manual,Second Owner,21.1 kmpl,814 CC,55.2 bhp,74.5Nm@ 4000rpm,5.0
7117,Chevrolet Tavera Neo 3 LT 9 Seats BSIII,2016,900000,100000,Diesel,Individual,Manual,First Owner,13.58 kmpl,2499 CC,72.4 bhp,171Nm@ 1800rpm,9.0
2606,Maruti Swift VDI,2013,375000,77000,Diesel,Individual,Manual,First Owner,22.9 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4931,Tata Manza Aura (ABS) Quadrajet BS IV,2012,300000,70000,Diesel,Individual,Manual,Third Owner,21.12 kmpl,1248 CC,88.8 bhp,200Nm@ 1750-3000rpm,5.0
3264,Ford Figo Diesel EXI,2012,220000,100000,Diesel,Individual,Manual,Second Owner,20.0 kmpl,1399 CC,68 bhp,160Nm@ 2000rpm,5.0
1653,Hyundai i10 Sportz Option,2009,170000,90000,Petrol,Individual,Manual,Second Owner,20.36 kmpl,1197 CC,78.9 bhp,111.8Nm@ 4000rpm,5.0
2607,Volkswagen Vento Diesel Highline,2012,375000,90000,Diesel,Individual,Manual,First Owner,20.54 kmpl,1598 CC,103.6 bhp,250Nm@ 1500-2500rpm,5.0
2732,Hyundai i10 Magna 1.1L,2012,225000,110000,Petrol,Individual,Manual,First Owner,19.81 kmpl,1086 CC,68.05 bhp,99.04Nm@ 4500rpm,5.0

In [8]:
car_price.isnull().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [16]:
#filling missing value and dropping useless columns
#dropping useless columns
car_price.drop(['torque','owner'],inplace=True,axis=1)

In [17]:
car_price

,name,year,selling_price,km_driven,fuel,seller_type,transmission,mileage,engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,23.4 kmpl,1248 CC,74 bhp,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,21.14 kmpl,1498 CC,103.52 bhp,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,17.7 kmpl,1497 CC,78 bhp,5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,23.0 kmpl,1396 CC,90 bhp,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,16.1 kmpl,1298 CC,88.2 bhp,5.0
...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,18.5 kmpl,1197 CC,82.85 bhp,5.0
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,16.8 kmpl,1493 CC,110 bhp,5.0
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,19.3 kmpl,1248 CC,73.9 bhp,5.0
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,23.57 kmpl,1396 CC,70 bhp,5.0
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,23.57 kmpl,1396 CC,70 bhp,5.0

In [18]:
#filling missing values or fillna method
car_price.interpolate()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,mileage,engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,23.4 kmpl,1248 CC,74 bhp,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,21.14 kmpl,1498 CC,103.52 bhp,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,17.7 kmpl,1497 CC,78 bhp,5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,23.0 kmpl,1396 CC,90 bhp,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,16.1 kmpl,1298 CC,88.2 bhp,5.0
...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai i20 Magna,2013,320000,110000,Petrol,Individual,Manual,18.5 kmpl,1197 CC,82.85 bhp,5.0
8124,Hyundai Verna CRDi SX,2007,135000,119000,Diesel,Individual,Manual,16.8 kmpl,1493 CC,110 bhp,5.0
8125,Maruti Swift Dzire ZDi,2009,382000,120000,Diesel,Individual,Manual,19.3 kmpl,1248 CC,73.9 bhp,5.0
8126,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,23.57 kmpl,1396 CC,70 bhp,5.0
8127,Tata Indigo CR4,2013,290000,25000,Diesel,Individual,Manual,23.57 kmpl,1396 CC,70 bhp,5.0

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
#x axis always in double brackets
x = car_price[['name','year','selling_price','km_driven','fuel','seller_type','transmission','mileage','engine','max_power','seats']]

In [21]:
y =car_price['selling_price'] #target variable or dependent variable

In [23]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=1)

In [24]:

x_train

,name,year,selling_price,km_driven,fuel,seller_type,transmission,mileage,engine,max_power,seats
2246,Chevrolet Sail 1.2 LS ABS,2015,350000,50000,Petrol,Individual,Manual,18.2 kmpl,1199 CC,82.4 bhp,5.0
2095,Chevrolet Optra Magnum 2.0 LT BS3,2008,225000,120000,Diesel,Individual,Manual,16.52 kmpl,1991 CC,123.7 bhp,5.0
3290,Hyundai Grand i10 Magna,2014,370000,60000,Petrol,Individual,Manual,18.9 kmpl,1197 CC,82 bhp,5.0
6868,Maruti Alto 800 VXI,2020,360000,5000,Petrol,Individual,Manual,22.05 kmpl,796 CC,47.3 bhp,5.0
6895,Mahindra XUV500 W9 2WD,2018,1350000,40000,Diesel,Individual,Manual,16.0 kmpl,2179 CC,138 bhp,7.0
...,...,...,...,...,...,...,...,...,...,...,...
7935,Maruti 800 AC,1999,40000,100000,Petrol,Individual,Manual,16.1 kmpl,796 CC,37 bhp,4.0
5192,Hyundai i20 Active 1.4,2016,580000,152000,Diesel,Individual,Manual,21.19 kmpl,1396 CC,88.73 bhp,5.0
3980,Hyundai EON Era Plus,2013,190000,70000,Petrol,Individual,Manual,21.1 kmpl,814 CC,55.2 bhp,5.0
235,Maruti Ritz LDi,2010,250000,110000,Diesel,Individual,Manual,21.1 kmpl,1248 CC,73.9 bhp,5.0
5157,Maruti Baleno Delta 1.2,2016,480000,65755,Petrol,Individual,Manual,21.4 kmpl,1197 CC,83.1 bhp,5.0

In [27]:
len(y_test)

2439

In [29]:
from sklearn.linear_model import LinearRegression
reg_model=LinearRegression()

In [30]:
#now fit our model 
reg_model.fit(x_train,y_train)
#it shows error beacuse we have some string in our data so we will change it in next step by binary numbers

ValueError: could not convert string to float: 'Chevrolet Sail 1.2 LS ABS'